### ISSUE TITLE
Missing nodes on when calling Depthfirst.Traverse.PostOrder

### ISSUE THREAD

**Issue by panosonasis** [Dirkster99/TreeLib#2]
Traverse PostOrder does not return all nodes of the tree when the first child of a node has even number of children.For example if you have a tree with A as root node and it has 3 children B,C and D and if the first one of the previous children (B) has even number of child nodes then you will not get back all the nodes.More specific it will return only A ,B node and the children of B node but not C and D with their childs.I believe that there is a need for an additional code in the lines below.

https://github.com/Dirkster99/TreeLib/blob/b682d7647223b92ab764641a68af915f02a8cdd7/source/Shared/Depthfirst/TraversePostOrder.cs#L79-L84

**Comment by Dirkster99** [comment]
Hi, I've seen this problem in my unit tests before just never got around to actually fixing it :-( but the good new is that I think I fixed it now :-)

The fixed solution is in a seperate branch: [Depthfirst.Traverse.PostOrder](https://github.com/Dirkster99/TreeLib/tree/Depthfirst.Traverse.PostOrder)
- Would you be able to test this for me and let me know if you see any issues with it?

I found that the old traversal structure was not too useful here because it had no direct readable states towards  whether:
- a node has been visited 
- a nodes children have been visited and so forth

So, I redesigned the algorithm using the private utility class:
`TreeLib.Depthfirst.Traverse.VisitElement<T>`

This class allows me tho keep the state in very simple way and yield each node in a simple while loop as you can see in the static `IEnumerable<T>PostOrderIterator<T>(...)` method in TreeLib.Depthfirst.Traverse.

The case you are reporting is this:
![tree](https://user-images.githubusercontent.com/2129700/60686383-b3d0a300-9ea8-11e9-8c72-fc89cfffc2dc.png)

This structure is tested in a unit test in TreeLibNugetUnitTests.CoreTests.TestMethod8() and does no longer return an error. I have added one or 2 more unit tests here for good measure but I think this is fine. Would you want to add more test patterns? If so, please let me know also...

Thanks for your detailed feedback.

**Comment by panosonasis** [comment]
First of all thanks for your quick response.So after a brief testing everything seems to work correctly.If i find something else i will keep you posted.Thanks!
